### ISSUE TITLE
Support K8s ingress controllers with URL rewrite

### ISSUE THREAD

**Issue by orenzp** [microsoft/DurableFunctionsMonitor#52]
Hello,
I set up the DFM on our Kubernetes cluster using the instructions provided in the docs, then I added a service resource and an ingress resource.
The ingress publishes the DFM under path `/dfm`. but when I try to access the endpoint I get a white screen on the browser and it seems that the DFM deployment redirects the browser to the root of the URL instead under the path `/dfm`

![image](https://user-images.githubusercontent.com/25840401/187679769-e62b1c02-4289-404d-9aa7-c6fbf47f5874.png)

Has anyone been able to publish the DFM via ingress? Below is the config for my ingress resources using the Nginx rewrite rule.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: dfm
  namespace: durablefunctions
spec:
  tls:
  - hosts:
    - example.dev.dom.com
    secretName: dev-ingress-tls
  rules:
  - host: example.dev.dom.com
    http:
      paths:
      - backend:
          service:
            name: dfm
            port:
              number: 8080
        path: /dfm(/|$)(.*)
        pathType: Prefix
```
